### PR TITLE
Improve typehints in lock.py

### PR DESCRIPTION
**Pull request by aviv-ebates**
- The constructors take an instance of type `BaseCache`, not `Type[]`
- Mypy doesn't consider `True` to be a type.

### CODE REVIEW

**Comment by argaen** [comment]
thanks @aviv-ebates! can you fix the syntax errors? no need to import the `Type` class anymore

**Comment by aviv-ebates** [comment]
hey @argaen , I've fixed the `import`, but it kinda looks like the tests are broken with `unknown hook 'pytest_namespace'`....

**Comment by argaen** [comment]
Oh wow, seems tests started failed since yesterday, probably a rogue dependency for testing. Will check and then rebase this branch with master then to see if build passes

**Comment by aviv-ebates** [comment]
thanks!

**Comment by argaen** [comment]
thanks for the contribution! :)

**Pull request merged**
