### PR TITLE
Add MessagePackSerializer

### LINKED ISSUE #362: Add msgpack serialization

### PR DESCRIPTION
**Pull request by ahopkins**
Fixes #362

### CODE REVIEW

**Comment by ahopkins** [comment]
See #362

**Comment by argaen** [comment]
Thanks for the contribution! I won't have a laptop until the 9th. I'll check the builds and all that and then merge and do a new release :)

**Comment by argaen** [comment]
@ahopkins the `msgpack` requirement is missing in `setup.py` :). Without it build can't pass

**Comment by ahopkins** [comment]
Got it. I'll add, and I also want to add use_list=False otherwise it cannot handle deaerializing dictionaries.

Adam Hopkins

**Comment by argaen** [comment]
I've added some changes to finish this MR and pass the tests. I have removed the `use_list` option because instead of hardcoding it I want to allow the user to pass it in the constructor. Next MR will be about this :).

Once I have the next MR ready and MR will do a new release with all this.

Thanks!

**Comment by ahopkins** [comment]
Awesome! Much better idea.

**Pull request merged**
